### ISSUE TITLE
KSP Installation not found

### ISSUE THREAD

**Issue by WGPSenshi** [cerebrate/x64-unfixer#2]
This is not a bug, but rather an enhancement request :) .

The solution for #1 fix (thanks for that), searching the KSP installation by using the windows add/remove does cause a new issue: KSP is portable (it's even distributed as a .zip for non-Steam-users). As in: Unpack the zip and just run the exe. Windows registry never knows something happened.

Proposed solution:
If no windows prog entry is found, assume the unfixer is launched from the main game dir (or gamedata subdir?). That's what I always did before, and if others do it differently, it shouldn't be hard to teach them  (a single console output comment as in "Unable to find KSP. Place this exe in the main game dir." should be enough).

**Comment by cerebrate** [comment]
Implemented in 1.5.0.0.
